name: Front
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'front/**'

jobs:
  front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run test:e2e --host
          working-directory: front
